### ISSUE TITLE
Dummy fighters are displayed to the fighter

### ISSUE THREAD

**Issue by deweydot** [nickhailer/CheatyMagesAlpha#16]
When a fighter is ejected by the judge they are replaced by a dummy fighter. This is only supposed to happen in the background and not be shown the UI but it is. Consider replacing the judge eject implementation.

**Comment by deweydot** [comment]
This will be assigned to Tyler

**Comment by uyeno24** [comment]
I fixed this issue by making sure when replacing the fighter card with dummy fighter to not put it back into the deck.
