### ISSUE TITLE
Bug with "Discard Button"

### ISSUE THREAD

**Issue by devamp** [nickhailer/CheatyMagesAlpha#7]
There was a bug I caught where pressing the discard button would crash your game instantly. I noticed that in the human player under line 116 where you have the switch case for "discard", the for-loop in that statement was looping out of bounds for the array causing a ArrayIndexOutOfBoundsException. I fixed the bug and wrote about it in my project review about this game but I'll also include it in this issue. 
![error1](https://user-images.githubusercontent.com/24514708/115126731-419a5700-9f86-11eb-8044-3fbd37f27887.PNG)

**Comment by deweydot** [comment]
This bug has been fixed on my branch
