### ISSUE TITLE
Bug: Discarding during the wrong phase

### ISSUE THREAD

**Issue by devamp** [nickhailer/CheatyMagesAlpha#8]
I found out that as soon as I start the game, instead of selecting my fighters and placing bets, if I just click a spell card and discard it, it was discarding that card. From then on I could keep clicking discard and it would discard all of the spells (I think) until the game crashed. This shouldn’t be possible because the player should not be able to discard until it is the discarding phase. I’m not sure what the root of this problem is, but I think it might be related to drawing a discarded card.

![erroerrror](https://user-images.githubusercontent.com/24514708/115128920-13bd0e80-9f96-11eb-8c5e-a53b5b6fb50c.PNG)

**Comment by deweydot** [comment]
This has been fixed.
